"""empty message

Revision ID: 4abe5aa0b543
Revises: 011f46b4f41d
Create Date: 2018-03-18 01:05:06.524195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abe5aa0b543'
down_revision = '011f46b4f41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'presencelists', ['event_id'])

    op.create_table('event_count',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['presencelists.event_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id'),
    sa.UniqueConstraint('user_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presencelists', type_='unique')
    op.drop_table('event_count')
    # ### end Alembic commands ###
