"""empty message

Revision ID: a428d452c9c5
Revises: 
Create Date: 2017-12-02 22:19:46.499930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a428d452c9c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presencelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conn_type', sa.String(length=128), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presencelists_pin'), 'presencelists', ['pin'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presencelists_pin'), table_name='presencelists')
    op.drop_table('presencelists')
    # ### end Alembic commands ###
