"""empty message

Revision ID: b3ded8536952
Revises: 48a2ceb37d6c
Create Date: 2017-12-31 17:00:15.712671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ded8536952'
down_revision = '48a2ceb37d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipbanns',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=False),
    sa.Column('failed_tries', sa.Integer(), nullable=False),
    sa.Column('time_ban_start', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipbanns')
    # ### end Alembic commands ###
